conf.py, formal.rst, index.rst, reference/formal_sectionB.rst, reference/formal_sectionC.rst, reference/index_sectionB.rst, reference/index_sectionC.rst, reference/informative/informB10_test_value1.rst, reference/informative/informB11_reset_value1.rst, reference/informative/informB12_math1.rst, reference/informative/informB12_math2.rst, reference/informative/informB15_connection2.rst, reference/informative/informB15_connection5.rst, reference/informative/informB16_map_variables2.rst, reference/informative/informC01_imports.rst, reference/informative/informC03_interpretation_of_units2.rst
=> Added space into CellML2.0 --> CellML 2.0

conf.py, reference/informative/informB1_model1.rst, reference/libcellml/libcellmlB1.rst, reference/sectionA_definitions.inc, reference/sectionC_interpretation.inc
Reverts cellml/cellml-specification#68
Not sure how this got merged, it's my magical git powers at work again ... it certainly wasn't meant to be :(
=> Revert "Addresses i60, i63 re imports of units and components"

reference/sectionA_definitions.inc
=> I89 contact email

reference/sectionA_definitions.inc
I believe this accurately captures people's contributions to the CellML 2.0 specification. (if I get the PR correct this time!) will close cellml/cellml-specification#91
=> Updating author and contributor lists

src/reference/sectionA_definitions.inc
=> Add link to comment infoitems

src/reference/sectionC_interpretation.inc
=> Improved language for interpretation of imports.

src/reference/formal_and_informative/specA2.rst, src/reference/informative/informA2_4.rst, src/reference/informative/informA2_6.rst
Addresses #55 
Rendered version is here: https://cellml-specification-dev.readthedocs.io/en/i55_ids_and_imports_informative/reference/formal_and_informative/specA2.html
=> i55 Writing informative section for 1.2.6

src/reference/sectionB_elements.inc
=> Added must-be-identifier for reset variables

src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Addresses #153 
Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i153_3_7_reword_normative/reference/formal_and_informative/specC07_effect_of_units_on_variables.html
=> Changes to 2.8 and 3.7 as per discussion

src/reference/sectionC_interpretation.inc
Taking Keri's comments from #191 on board
=> Slight change to reset wording. 

src/normative_only_index.rst
See #197
Plus some changes of my own
=> Tweaks to preamble of norm spec.

src/reference/informative/informA1.rst, src/reference/sectionA_definitions.inc
=> Changed character classes to consistently be numericAL or alphabeticAL

src/reference/sectionA_definitions.inc
change any or none to zero or more
=> Resolve any or none

src/conf.py, src/reference/sectionD_references.inc
Addresses #243 
Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i243_links_hash/reference/index_sectionD.html
=> i243 remove hash from rfc link

src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Fixes for various new tickets about details in the normative spec.
Most by keri, some by me.
=> Various small fixes

README.rst, src/conf.py
Related to, but does not fully address #167.
=> Made normative-only the default build.

src/conf.py, src/reference/informative/informC09_interpretation_of_encapsulation2.rst, src/reference/informative/informC09_interpretation_of_encapsulation3.rst, src/reference/informative/informC10_interpretation_of_map_variables3.rst, src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Looking at fixing #282. and #278 
(As well as fixing some build warnings.)
=> Using the power of numref.

.gitignore, README.rst, requirements.txt
Closes #293.
With these (and #154) it works for me in a virtual environment
=> Updated requirements and gitignore file.

README.rst
=> Added latex info to README.rst. 

src/reference/informative_preamble.inc
=> I300 update preamble wording

src/reference/formal_and_informative/specC07_effect_of_units_on_variables.rst, src/reference/informative/informC07_effect_of_units_on_variables.rst, src/reference/sectionC_interpretation.inc
Closes #140 
Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i140_informative_3_7_effect_of_units_on_variable/reference/formal_and_informative/specC07_effect_of_units_on_variables.html
=> I140 informative 3 7 effect of units on variable
