cellml/cellml-specification

conf.py
The current PDF builder in our readthedocs configuration can't support more than one PDF at once.  This PR removes the line that's causing build errors; the PDF served will be only the formal normative spec.
=> Remove twin build for PDFs

reference/sectionA_definitions.inc
Changed "zero or more" to "any or none" in A.2.3. 
Addresses #34
=> I34 semantic equivalence rewording

reference/sectionC_interpretation.inc
Addresses #59
Rendered version here: https://cellml-specification-dev.readthedocs.io/en/i59_connections_in_sectionc/reference/formal_and_informative/specC09_interpretation_of_encapsulation.html
NB order of items in section C changed elsewhere - it's now:
1. Interpretation of imports
2. Units reference
3. Interpretation of units
4. Component reference
5. Variable reference
6. Interpretation of initial values
7. Effect of units on variables
8. Interpretation of mathematics
9. Interpretation of encapsulation
10. Interpretation of map_variables
11. Interpretation of variable resets
=> i59 C.9.7 redundancy

reference/sectionA_definitions.inc
Addresses #89 by (re)changing the contact email address to editors@cellml.org
=> I89 editors email

conf.py, reference/informative/informB1_model3.rst, reference/informative/informB3_import_units1.rst
Removes leftover references to libCellML, addresses [this comment](https://github.com/cellml/cellml-specification/pull/99#discussion_r399035193) and #102
=> Remove libcellml refs

src/reference/sectionC_interpretation.inc
Fixes #149, tidying up the rules. The intro paragraph is explicit in the elements and attributes being discussed so no longer a need for the catch-all clause in the rules.
=> Tidy up 3.4, issue 149

src/reference/sectionA_definitions.inc
- condensed identifier definition (#181 and #182 )
- the equality rule said "have identical sequences", which I think meant "have sequences that are entirely identical", but could be taken to mean "have identical sequences anywhere in the string", e.g. "hello_me" == "hello_you" since both have an identical sequence of characters ("hello_").
- Someone might still want to argue that an identifier isn't a sequence itself so that "are" is wrong? Not me!
=> Identifier rules

src/reference/sectionA_definitions.inc
Addresses #201 
Agree in meeting to remove ref to both namespaces, but come to think of it, it's unusual for us to decree something about the MathML namespace, so this should stay in but with slightly altered wording
=> Tiny change to equivalence definition.

src/reference/sectionB_elements.inc
=> CellML Namespace is now consistently a link. 

src/reference/sectionA_definitions.inc, src/reference/sectionB_elements.inc
See #197.
We consistently use ; and end with . now for lists with small items.
For lists with longer items we don't necessarily do this, and I'm very happy about that as it improves the readability.
=> Tiny list punctuation fixes. 

src/reference/sectionA_definitions.inc
- No need to mention the "REQUIRED", "SHOULD", "SHOULD NOT", "RECOMMENDED" and "OPTIONAL" keywords. They are never used in the spec.
- CellML infoset: "In this specification[,] such infosets are assumed to be CellML 2.0 infosets." (missing comma)
- Whitespace character: list the Unicode characters in order, i.e. U+0009, U+000A, U+000D or U+0020.
(w.r.t. to the comma, we do it elsewhere in the same chapter, so doing it here too)
=> Updates to terminology section wording as suggested in #197.

src/reference/sectionB_elements.inc
See #197.
- import was the only element that didn't specify who its parent was
- wording was slightly inconsistent across elements
=> Consistent "which appears as a child of" wording for all elements

src/reference/sectionA_definitions.inc
A char info item is a single char. See #197.
=> Change to whitespace-in-elements wording

src/reference/sectionB_elements.inc
See #197 
The "logical" order is subjective, so we use alphabetical (as as already done in the model element).
Unlike CellML 1.0/1.1, we do not define or imply a certain "best" ordering of elements.
=> Chapter 2: Lists of children are alphabetical.

src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
=> Consistently using 'identical' when comparing identifiers.

src/conf.py
=> Stopped cross-references in PDF from showing up in italics.

src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Fixes #239.
There's a lot of links that aren't important enough to interrupt the flow of the text with a section number, so have left them as they are.
Also links to tables for some reason can't be numrefs, so haven't touched those.
=> Changed 'see X' links from `:ref:` to `:numref:`

src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Added rule saying the component referenced by a component_ref element must be unique, which prevents cycles in the encapsulation digraph.
See #261
=> Encapsulation loops

src/conf.py, src/reference/sectionA_definitions.inc, src/reference/sectionB_elements.inc, src/reference/sectionD_references.inc
Addresses #280 and #288 
Numbered references throughout the text so that people who are reading on paper can follow them.  
Global numbering is not supported (ie, can't use [1] etc) as that's reserved for local footnotes.  I've used [Ref_1] ... but open to other ideas ...
Rendered version is here: https://cellml-specification-dev.readthedocs.io/en/i280_numbering_references/reference/formal_only/specA2.html#cellml-and-xml
=> I280 numbering references

requirements.txt, src/conf.py
Closes #314 
... but ... this currently is proof of concept as it requires a branch from the hoverxref repo.  It can be merged now if we're desperate, or we can wait for it to be included in their update.
See change in the requirements file that would need to be reverted.  
Rendered docs are here: https://cellml-specification-dev.readthedocs.io/en/i314_numref_hoverxref/reference/formal_and_informative/specB09.html
=> I314 numref hoverxref

src/reference/informative/informA2_5.rst, src/reference/informative/informB12_math3.rst, src/reference/informative/informB14_component_ref1.rst, src/reference/informative/informB15_connection2.rst, src/reference/informative/informB1_model3.rst, src/reference/informative/informB3_import_units1.rst, src/reference/informative/informB4_import_component1.rst, src/reference/informative/informB5_units1.rst, src/reference/informative/informB6_unit2.rst, src/reference/informative/informB7_component1.rst, src/reference/informative/informB7_component2.rst, src/reference/informative/informB7_component3.rst, src/reference/informative/informB8_variable1.rst, src/reference/informative/informC01_imports.rst, src/reference/informative/informC07_effect_of_units_on_variables.rst, src/reference/informative/informC08_interpretation_of_mathematics2.rst, src/reference/informative/informC08_interpretation_of_mathematics3.rst, src/reference/informative/informC09_interpretation_of_encapsulation3.rst, src/reference/informative/informC10_interpretation_of_map_variables5.rst
Addresses #328 
Where appropriate, use numref not ref throughout the informative spec.  
See eg: https://cellml-specification-dev.readthedocs.io/en/i328_numref_in_informative_blocks/reference/formal_and_informative/specB07.html reference in first See more block.
=> Changed ref into numref where appropriate in informative blocks

src/reference/index_sectionE.rst
=> Move resets to be first example

requirements.txt, src/conf.py, src/reference/formal_sectionA.rst, src/reference/formal_sectionB.rst, src/reference/formal_sectionC.rst, src/reference/formal_sectionD.rst, src/reference/sectionA_definitions.inc, src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
The manual heading numbering didn't work for the LatexPDF build. At least I have not yet found a way to get around the issue of Latex adding heading numbers automatically and having a contents available in the generated document.  Reverting the manual heading numbering to release the next version of the spec.
=> Revert manual heading numbering.

src/conf.py, src/reference/sectionB_elements.inc, src/reference/sectionC_interpretation.inc
Doing this probably because of a bug in sphinx.
=> Hard code name for table references

src/conf.py, src/master_index.rst, src/normative_only_index.rst, src/reference/sectionB_elements.inc
Small fix to definition of `component_ref`.
Put heading numbers back in place for `html` build of documentation.
Fix cross referencing issue for `html` build.
=> Spec correction for `component_ref`
